version: 1.0
runtime: nodejs18
build:
  commands:
    - npm install
run:
  command: npm start
  network:
    port: 8080

    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
