name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    ssteps:
  - name: Setup Miniconda
    uses: conda-inc/conda-build-action@v1
    with:
      installer: Miniforge3
      python-version: 3.10

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          auto-update-conda: true
          python-version: '3.10'
          environment-file: environment.yml
          activate-environment: base

      - name: Install dependencies
        run: |
          conda install -y flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
